name: "Install AWS CLI"
description: "Install AWS CLI on a Linux host"
inputs:
  version:
    description: "1=latest version of v1, 2=latest version of v2, #.#.#=specific version"
    required: false
    default: "2"
runs:
  using: "composite"
  steps:
    - run: echo "::set-output name=version::$(echo $INPUT_VERSION)"
      shell: bash
    - run: ${{ github.action_path }}/entrypoint.sh $INPUT_VERSION
      shell: bash
