name: "Install AWS CLI"
description: "Install AWS CLI on a Linux host"
inputs:
  version:
    description: "1=latest version of v1, 2=latest version of v2, #.#.#=specific version"
    required: false
    default: 2
outputs:
  version:
    description: "The AWS CLI version that was installed"
    value: ${{ steps.entrypoint.outputs.version }}

runs:
  using: "composite"
  steps:
    - id: set-env-vars
      run: echo "AWS_CLI_VERSION=${{ inputs.version }}" >> $GITHUB_ENV
      shell: bash
    - id: entrypoint
      run: echo "::set-output name=version::$(${{ github.action_path }}/entrypoint.sh $AWS_CLI_VERSION)"
      shell: bash
