name: dispatch-test-action

on:
  push:
  release:
  workflow_dispatch:

jobs:
  dispatch_test_action:
    runs-on: ubuntu-latest
    steps:
      - name: Workflow Dispatch
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: test-action
          token: ${{ secrets.GH_TOKEN }}
          ref: master
          repo: unfor19/install-aws-cli-action-test
