name: test

on: [push, workflow_dispatch]

jobs:
  dispatch_test_action:
    name: Dispatch test action
    runs-on: ubuntu-latest
    env:
      GH_OWNER: unfor19
      GH_REPO: install-aws-cli-action-test
      GH_WORKFLOW: test-action.yml
      GH_REF: master
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
    steps:
      - name: Workflow Dispatch
        run: |
          curl -X POST -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: Bearer ${GH_TOKEN}" \
            https://api.github.com/repos/${GH_OWNER}/${GH_REPO}/actions/workflows/${GH_WORKFLOW}/dispatches \
            -d '{"ref":"'${GH_REF}'"}'

  test_amd64:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        include:
          - TEST_NAME: "Latest v2"
            AWS_CLI_VERSION: "2"
          - TEST_NAME: "Specific v2"
            AWS_CLI_VERSION: "2.0.30"
          - TEST_NAME: "Latest v1"
            AWS_CLI_VERSION: "1"
          - TEST_NAME: "Specific v1"
            AWS_CLI_VERSION: "1.16.312"
          - TEST_NAME: "No Input"
    name: Test amd64 ${{ matrix.TEST_NAME }} ${{ matrix.AWS_CLI_VERSION}}
    steps:
      - uses: actions/checkout@v2
      - name: test on Runner
        env:
          AWS_CLI_VERSION: "${{ matrix.AWS_CLI_VERSION}}"
          AWS_CLI_ARCH: "${{ matrix.AWS_CLI_ARCH }}"
        run: |
          sudo ./entrypoint.sh

  test_arm64:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        include:
          - TEST_NAME: "Latest v2"
            AWS_CLI_VERSION: "2"
          - TEST_NAME: "Specific v2"
            AWS_CLI_VERSION: "2.0.30"
    name: Test arm64 ${{ matrix.TEST_NAME }} ${{ matrix.AWS_CLI_VERSION}}
    steps:
      - uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}
      - name: Test in Docker
        env:
          AWS_CLI_VERSION: "${{ matrix.AWS_CLI_VERSION}}"
          AWS_CLI_ARCH: "arm64"
          DOCKER_TAG: "install-aws-cli-action"
        run: |
          docker buildx build --platform arm64 -t "$DOCKER_TAG" .
          docker run --rm -it -e AWS_CLI_VERSION -e AWS_CLI_ARCH "$DOCKER_TAG"
