name: test

on: [push, workflow_dispatch]

jobs:
  dispatch_test_action:
    name: Dispatch test action
    runs-on: ubuntu-latest
    env:
      GH_OWNER: unfor19
      GH_REPO: install-aws-cli-action-test
      GH_WORKFLOW: test-action.yml
      GH_REF: master
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
    steps:
      - name: Workflow Dispatch
        run: |
          curl -X POST -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: Bearer ${GH_TOKEN}" \
            https://api.github.com/repos/${GH_OWNER}/${GH_REPO}/actions/workflows/${GH_WORKFLOW}/dispatches \
            -d '{"ref":"'${GH_REF}'"}'

  test:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        include:
          - TEST_NAME: "Latest v2"
            AWS_CLI_VERSION: "2"
          - TEST_NAME: "Specific v2"
            AWS_CLI_VERSION: "2.0.30"
          - TEST_NAME: "Latest v1"
            AWS_CLI_VERSION: "1"
          - TEST_NAME: "Specific v1"
            AWS_CLI_VERSION: "1.16.312"
          - TEST_NAME: "No Input"
    name: Test ${{ matrix.TEST_NAME }}
    steps:
      - uses: actions/checkout@v2
      - name: test on Runner
        env:
          AWS_CLI_VERSION: "${{ matrix.AWS_CLI_VERSION}}"
          AWS_CLI_ARCH: "${{ matrix.AWS_CLI_ARCH }}"
        run: |
          sudo ./entrypoint.sh
